print("="*60)
print("CAREER INSIGHTS FOR ASPIRING DATA SCIENTISTS 2025-26")
print("="*60)

print("\n1. WHICH ROLE PAYS THE MOST?")
print("-"*40)
print("Applied Scientist:         ~$185,000 = #1")
print("Product Manager:           ~$180,000 = #2")
print("Machine Learning Engineer: ~$177,000 = #3")
print("Research Scientist:        ~$176,000 = #4")
print("AI Engineer:               ~$158,000 = #9")
print("(Source: Graph 1 — Top 10 Paying Job Titles)")


print("\n2. HOW MUCH DOES EXPERIENCE MATTER?")
print("-"*40)
print("Entry Level:    $80,000")
print("Mid Level:      $130,000")
print("Senior:         $160,000")
print("Executive:      ~190,000")
print("From Entry to Executive, salary increased by 2.5x")
print("(Source: Graph 2 — Salary by Experience)")

print("\n3. IS REMOTE WORK STILL VALUABLE?")
print("-"*40)
print("On-site Median Salary:     $135,000")
print("Hybrid Median Salary:      $70,000")
print("Fully Remote Median Salary: $140,000")
print("KEY FINDINGS:")
print("Remote and On-site salaries are almost EQUAL")
print("Hybrid jobs pay the least among all work types")
print("(Source: Graph 3  Salary Distribution by Remote Category)")

print("\n4. WHICH COUNTRIES PAY BEST?")
print("-"*40)
print("Qatar (QA):         ~$300,000")
print("Venezuela (VE):     ~$195,000")
print("United States (US): ~$155,000")
print("(Source: Graph 4 — Top 10 Paying Countries)")

print("\n5. DOES COMPANY SIZE AFFECT SALARY SIGNIFICANTLY?")
print("-"*40)
print("Small  Company Average Salary: $87,000")
print("Medium Company Average Salary: $145,000")
print("Large  Company Average Salary: $133,000")
print("KEY FINDINGS:")
print("Surprising: Bigger is NOT always better for salary!")
print("ML Feature Importance confirms:")
print("  company_size = only 2% impact on salary")
print("(Source: Graph 5 — Average Salary by Company Size)")

print("\n6. MOST IMPORTANT FACTOR FOR SALARY?")
print("-"*40)
print("→ Experience/Seniority = 90% impact on salary!")
print("→ Work Year            = 5% impact on salary")
print("→ Remote Work          = only 3% impact on salary")
print("→ Company Size         = only 2% impact on salary")

print("\n7. ADVICE FOR STUDENTS FROM PAKISTAN/INDIA/BANGLADESH")
print("-"*40)
print("→ Build experience — 90% salary impact")
print("→ Target AI/ML roles — highest paying field")
print("→ Remote jobs = same salary as on-site")
print("→ Medium companies offer best salaries")
print("→ Entry salary ~$80,000 can grow to ~$190,000")
print("="*60)